// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwxyglwncutvunkqonxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3eHlnbHduY3V0dnVua3FvbnhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjc4MjUsImV4cCI6MjA2NzgwMzgyNX0.bPaf6JjAV5CuhLbIjLjilP4ZQ2mItzey2nQtcGyRt7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});